version: "3.9"
services:
  gol:
    build: ./gol
    ports:
      - 8080:8080
    volumes: 
      - type : volume
        source : loggol
        target : /var/log
    networks:
      - qtnetwork
  spc:
    build: ./spc
    ports:
      - 8081:8080
    volumes: 
        - type : volume
          source : logspc
          target : /var/log
    networks:
       - qtnetwork

volumes: 
  logspc:
  loggol:
networks: 
  qtnetwork :
    driver : bridge
    